<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: common/empty.proto

namespace GPBMetadata\Common;

class PBEmpty
{
    public static $is_initialized = false;

    public static function initOnce() {
        $pool = \Google\Protobuf\Internal\DescriptorPool::getGeneratedPool();

        if (static::$is_initialized == true) {
          return;
        }
        $pool->internalAddGeneratedFile(
            '
]
common/empty.protocommon"
EmptyB.Z,github.com/zhihao0924/protobuf/golang/commonbproto3'
        , true);

        static::$is_initialized = true;
    }
}

